### ISSUE TITLE
障害が発生していたら

### ISSUE THREAD

**Issue by himaratsu** [meyasubaco/zatsu#14]
Herokuのログを確認する。

```
$ heroku login
$ heroku logs --app meyasubaco
```

meyasubaco のところは適当なアプリ名を入れる。

**Comment by shoma2da** [comment]
気付けないからそのうち監視システム入れないとダメだよねー。

**Comment by shoma2da** [comment]
https://handshakejp.slack.com/archives/general/p1455013280000433

**Comment by shoma2da** [comment]
https://github.com/meyasubaco/zatsu/issues/6（これと関連してそう。）

**Comment by shoma2da** [comment]
別のプロダクトで [papertrail](https://devcenter.heroku.com/articles/papertrail) を入れたんですが、良い感じでした！
各サーバに導入してみます。

* 設定一切不要で導入できる
* 無料で使える
* アラートメールや通知を出せる

**Comment by shoma2da** [comment]
ログがブラウザから見られるようになりました！
https://papertrailapp.com/groups/2552444/events

**Comment by shoma2da** [comment]
![image](https://cloud.githubusercontent.com/assets/2342648/13836962/297cca08-ec4a-11e5-885d-33192bdb3457.png)
サーバ別に絞り込みもできます！

**Comment by shoma2da** [comment]
![_2016-03-17_14_14_44](https://cloud.githubusercontent.com/assets/2342648/13837052/b9b0f888-ec4a-11e5-9ae3-02d7b59dac07.png)
サーバの管理画面からも飛べます。
