### ISSUE TITLE
Gmailの転送設定を完了させる

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/zatsu#21]
meyasubacojp@gmail.com

**Comment by shoma2da** [comment]
@himaratsu こんなの届いたかな？
![image](https://cloud.githubusercontent.com/assets/2342648/14064921/aa87dde2-f44f-11e5-9a58-0af10ad6f1c1.png)

**Comment by shoma2da** [comment]
@shibe97 Gmailに届いてる「確認メール」への対応が終わってないみたいなのでもう一度送りました！
対応お願いします！

**Comment by shibe97** [comment]
@shoma2da たぶん対応しました！

**Comment by shoma2da** [comment]
こんなのが届いていればOKです！
![image](https://cloud.githubusercontent.com/assets/2342648/14098154/e00c80f2-f5b3-11e5-871e-23558726eff5.png)

**Comment by shoma2da** [comment]
@shibe97 @himaratsu ↑のが届いてたらリアクションくださいー。二人ともOKになったらCloseします。

**Comment by shibe97** [comment]
@shoma2da きました！

**Comment by himaratsu** [comment]
@shoma2da きました！
